#define PLUS                             1
#define MINUS                            2
#define MULTIPLY                         3
#define DIVIDE                           4
#define EQUAL                            5
#define GREATER                          6
#define LESS                             7
#define GT_EQ                            8
#define LE_EQ                            9
#define NOT_EQ                          10
#define OR                              11
#define AND                             12
#define NOT                             13
#define SEMICOLON                       14
#define CREATE                          15
#define TABLE                           16
#define LEFT_PARENTHESES                17
#define RIGHT_PARENTHESES               18
#define COMMA                           19
#define PRIMARY_KEY                     20
#define CHAR                            21
#define INT_NUM                         22
#define INT                             23
#define DECIMAL                         24
#define BOOLEAN                         25
#define ID                              26
#define DROP                            27
