/* This file is automatically generated by Lemon from input grammar
** source file "parse.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include <stdio.h>
#include <iostream>
#include <assert.h>

#include "ast/node.h"
#include "ast/ddl.h"
#include "ast/dml.h"
#include "util/config.h"
#include "sql/lex.h"

static bool debug = true;

inline void debug_print(std::string info) {
    if (debug) {
        std::cout << info << std::endl;
    }
}
#line 46 "parse.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef PLUS
#define PLUS                            1
#define MINUS                           2
#define MULTIPLY                        3
#define DIVIDE                          4
#define EQUAL                           5
#define GREATER                         6
#define LESS                            7
#define GT_EQ                           8
#define LE_EQ                           9
#define NOT_EQ                         10
#define OR                             11
#define AND                            12
#define NOT                            13
#define SEMICOLON                      14
#define CREATE                         15
#define TABLE                          16
#define LEFT_PARENTHESES               17
#define RIGHT_PARENTHESES              18
#define COMMA                          19
#define PRIMARY_KEY                    20
#define CHAR                           21
#define INT_NUM                        22
#define INT                            23
#define DECIMAL                        24
#define BOOLEAN                        25
#define ID                             26
#define DROP                           27
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    dawnTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is dawnTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    dawnARG_SDECL     A static variable declaration for the %extra_argument
**    dawnARG_PDECL     A parameter declaration for the %extra_argument
**    dawnARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    dawnARG_STORE     Code to store %extra_argument into yypParser
**    dawnARG_FETCH     Code to extract %extra_argument from yypParser
**    dawnCTX_*         As dawnARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 42
#define YYACTIONTYPE unsigned char
#define dawnTOKENTYPE dawn::Token
typedef union {
  int yyinit;
  dawnTOKENTYPE yy0;
  dawn::IdentifierNode* yy2;
  dawn::CreateNode* yy3;
  dawn::DataTypeNode* yy7;
  dawn::StmtNode* yy23;
  dawn::DMLNode* yy24;
  dawn::ColumnDefNode* yy25;
  dawn::StmtListNode* yy35;
  dawn::CreateDefListNode* yy42;
  dawn::DropNode* yy56;
  dawn::CreateDefNode* yy66;
  dawn::DDLNode* yy75;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define dawnARG_SDECL dawn::StmtListNode* ast_root;;
#define dawnARG_PDECL ,dawn::StmtListNode* ast_root;
#define dawnARG_PARAM ,
#define dawnARG_FETCH dawn::StmtListNode* ast_root;=yypParser->;
#define dawnARG_STORE yypParser->=;
#define dawnCTX_SDECL
#define dawnCTX_PDECL
#define dawnCTX_PARAM
#define dawnCTX_FETCH
#define dawnCTX_STORE
#define YYNSTATE             18
#define YYNRULE              21
#define YYNRULE_WITH_ACTION  21
#define YYNTOKEN             28
#define YY_MAX_SHIFT         17
#define YY_MIN_SHIFTREDUCE   37
#define YY_MAX_SHIFTREDUCE   57
#define YY_ERROR_ACTION      58
#define YY_ACCEPT_ACTION     59
#define YY_NO_ACTION         60
#define YY_MIN_REDUCE        61
#define YY_MAX_REDUCE        81
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (46)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */     9,   62,   64,   81,   67,   68,   63,   64,   61,   67,
 /*    10 */    68,   60,   59,   65,   74,    8,   70,    4,   65,   11,
 /*    20 */    17,   15,    1,   53,   54,   55,   74,   12,   71,    4,
 /*    30 */     5,   16,   10,   56,   72,   75,   45,    3,   49,   56,
 /*    40 */     6,   13,   52,   14,    2,    7,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    28,   29,   30,   34,   32,   33,   29,   30,    0,   32,
 /*    10 */    33,   42,   40,   41,   34,   35,   36,   37,   41,   34,
 /*    20 */    15,   21,   14,   23,   24,   25,   34,   20,   36,   37,
 /*    30 */    16,   34,   27,   26,   38,   39,   18,   19,   18,   26,
 /*    40 */    17,   22,   18,   17,   17,   16,   42,   42,   42,   42,
 /*    50 */    42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
 /*    60 */    42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
 /*    70 */    42,   42,   42,   42,
};
#define YY_SHIFT_COUNT    (17)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (29)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */     5,    5,    7,    7,    0,   13,   13,   13,   18,    8,
 /*    10 */    14,   20,   23,   24,   19,   26,   27,   29,
};
#define YY_REDUCE_COUNT (7)
#define YY_REDUCE_MIN   (-31)
#define YY_REDUCE_MAX   (0)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -28,  -23,  -20,   -8,   -4,  -31,  -15,   -3,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */    66,   66,   58,   58,   58,   58,   58,   58,   58,   58,
 /*    10 */    58,   58,   58,   58,   58,   58,   58,   58,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  dawnARG_SDECL                /* A place to hold %extra_argument */
  dawnCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void dawnTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "PLUS",
  /*    2 */ "MINUS",
  /*    3 */ "MULTIPLY",
  /*    4 */ "DIVIDE",
  /*    5 */ "EQUAL",
  /*    6 */ "GREATER",
  /*    7 */ "LESS",
  /*    8 */ "GT_EQ",
  /*    9 */ "LE_EQ",
  /*   10 */ "NOT_EQ",
  /*   11 */ "OR",
  /*   12 */ "AND",
  /*   13 */ "NOT",
  /*   14 */ "SEMICOLON",
  /*   15 */ "CREATE",
  /*   16 */ "TABLE",
  /*   17 */ "LEFT_PARENTHESES",
  /*   18 */ "RIGHT_PARENTHESES",
  /*   19 */ "COMMA",
  /*   20 */ "PRIMARY_KEY",
  /*   21 */ "CHAR",
  /*   22 */ "INT_NUM",
  /*   23 */ "INT",
  /*   24 */ "DECIMAL",
  /*   25 */ "BOOLEAN",
  /*   26 */ "ID",
  /*   27 */ "DROP",
  /*   28 */ "stmt_list",
  /*   29 */ "stmt",
  /*   30 */ "ddl",
  /*   31 */ "dml",
  /*   32 */ "create",
  /*   33 */ "drop",
  /*   34 */ "identifier",
  /*   35 */ "create_def_list",
  /*   36 */ "create_def",
  /*   37 */ "col_name",
  /*   38 */ "column_def",
  /*   39 */ "data_type",
  /*   40 */ "sql",
  /*   41 */ "empty_stmt",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "sql ::= stmt_list",
 /*   1 */ "stmt_list ::= stmt",
 /*   2 */ "stmt_list ::= stmt_list SEMICOLON stmt",
 /*   3 */ "stmt ::= ddl",
 /*   4 */ "stmt ::= empty_stmt",
 /*   5 */ "empty_stmt ::=",
 /*   6 */ "ddl ::= create",
 /*   7 */ "ddl ::= drop",
 /*   8 */ "create ::= CREATE TABLE identifier LEFT_PARENTHESES create_def_list RIGHT_PARENTHESES",
 /*   9 */ "create_def_list ::= create_def",
 /*  10 */ "create_def_list ::= create_def_list COMMA create_def",
 /*  11 */ "create_def ::= col_name column_def",
 /*  12 */ "create_def ::= PRIMARY_KEY LEFT_PARENTHESES identifier RIGHT_PARENTHESES",
 /*  13 */ "col_name ::= identifier",
 /*  14 */ "column_def ::= data_type",
 /*  15 */ "data_type ::= CHAR LEFT_PARENTHESES INT_NUM RIGHT_PARENTHESES",
 /*  16 */ "data_type ::= INT",
 /*  17 */ "data_type ::= DECIMAL",
 /*  18 */ "data_type ::= BOOLEAN",
 /*  19 */ "identifier ::= ID",
 /*  20 */ "drop ::= DROP TABLE identifier",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to dawnAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void dawnInit(void *yypRawParser dawnCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  dawnCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef dawn_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to dawn and dawnFree.
*/
void *dawnAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) dawnCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    dawnCTX_STORE
    dawnInit(yypParser dawnCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* dawn_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  dawnARG_FETCH
  dawnCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void dawnFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef dawn_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void dawnFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  dawnFinalize(p);
  (*freeProc)(p);
}
#endif /* dawn_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int dawnStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int dawnCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   dawnARG_FETCH
   dawnCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   dawnARG_STORE /* Suppress warning about unused %extra_argument var */
   dawnCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  dawnTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    40,  /* (0) sql ::= stmt_list */
    28,  /* (1) stmt_list ::= stmt */
    28,  /* (2) stmt_list ::= stmt_list SEMICOLON stmt */
    29,  /* (3) stmt ::= ddl */
    29,  /* (4) stmt ::= empty_stmt */
    41,  /* (5) empty_stmt ::= */
    30,  /* (6) ddl ::= create */
    30,  /* (7) ddl ::= drop */
    32,  /* (8) create ::= CREATE TABLE identifier LEFT_PARENTHESES create_def_list RIGHT_PARENTHESES */
    35,  /* (9) create_def_list ::= create_def */
    35,  /* (10) create_def_list ::= create_def_list COMMA create_def */
    36,  /* (11) create_def ::= col_name column_def */
    36,  /* (12) create_def ::= PRIMARY_KEY LEFT_PARENTHESES identifier RIGHT_PARENTHESES */
    37,  /* (13) col_name ::= identifier */
    38,  /* (14) column_def ::= data_type */
    39,  /* (15) data_type ::= CHAR LEFT_PARENTHESES INT_NUM RIGHT_PARENTHESES */
    39,  /* (16) data_type ::= INT */
    39,  /* (17) data_type ::= DECIMAL */
    39,  /* (18) data_type ::= BOOLEAN */
    34,  /* (19) identifier ::= ID */
    33,  /* (20) drop ::= DROP TABLE identifier */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) sql ::= stmt_list */
   -1,  /* (1) stmt_list ::= stmt */
   -3,  /* (2) stmt_list ::= stmt_list SEMICOLON stmt */
   -1,  /* (3) stmt ::= ddl */
   -1,  /* (4) stmt ::= empty_stmt */
    0,  /* (5) empty_stmt ::= */
   -1,  /* (6) ddl ::= create */
   -1,  /* (7) ddl ::= drop */
   -6,  /* (8) create ::= CREATE TABLE identifier LEFT_PARENTHESES create_def_list RIGHT_PARENTHESES */
   -1,  /* (9) create_def_list ::= create_def */
   -3,  /* (10) create_def_list ::= create_def_list COMMA create_def */
   -2,  /* (11) create_def ::= col_name column_def */
   -4,  /* (12) create_def ::= PRIMARY_KEY LEFT_PARENTHESES identifier RIGHT_PARENTHESES */
   -1,  /* (13) col_name ::= identifier */
   -1,  /* (14) column_def ::= data_type */
   -4,  /* (15) data_type ::= CHAR LEFT_PARENTHESES INT_NUM RIGHT_PARENTHESES */
   -1,  /* (16) data_type ::= INT */
   -1,  /* (17) data_type ::= DECIMAL */
   -1,  /* (18) data_type ::= BOOLEAN */
   -1,  /* (19) identifier ::= ID */
   -3,  /* (20) drop ::= DROP TABLE identifier */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  dawnTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  dawnCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  dawnARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* sql ::= stmt_list */
#line 49 "parse.y"
{
    debug_print("sql: stmt_list");
    ast_root = yymsp[0].minor.yy35;
}
#line 961 "parse.c"
        break;
      case 1: /* stmt_list ::= stmt */
#line 54 "parse.y"
{
    debug_print("stmt_list: stmt");
    yylhsminor.yy35 = dawn::StmtListNode();
    yylhsminor.yy35->add_child(yymsp[0].minor.yy23);
}
#line 970 "parse.c"
  yymsp[0].minor.yy35 = yylhsminor.yy35;
        break;
      case 2: /* stmt_list ::= stmt_list SEMICOLON stmt */
#line 60 "parse.y"
{
    debug_print("stmt_list: stmt_list ';' stmt");
    yymsp[-2].minor.yy35->add_child(yymsp[0].minor.yy23);
    yylhsminor.yy35 = yymsp[-2].minor.yy35;
}
#line 980 "parse.c"
  yymsp[-2].minor.yy35 = yylhsminor.yy35;
        break;
      case 3: /* stmt ::= ddl */
#line 66 "parse.y"
{
    debug_print("sql: ddl");
    yylhsminor.yy23 = yymsp[0].minor.yy75;
}
#line 989 "parse.c"
  yymsp[0].minor.yy23 = yylhsminor.yy23;
        break;
      case 4: /* stmt ::= empty_stmt */
#line 71 "parse.y"
{
    debug_print("sql: empty_stmt");
    yymsp[0].minor.yy23 = new dawn::StmtNode(dawn::NodeType::kEmptyStmt);
}
#line 998 "parse.c"
        break;
      case 5: /* empty_stmt ::= */
#line 76 "parse.y"
{debug_print("empty_stmt");}
#line 1003 "parse.c"
        break;
      case 6: /* ddl ::= create */
#line 78 "parse.y"
{
    debug_print("ddl: create");
    yylhsminor.yy75 = new dawn::DDLNode(dawn::DDLType::kCreateTable);
    yylhsminor.yy75->add_child(yymsp[0].minor.yy3);
}
#line 1012 "parse.c"
  yymsp[0].minor.yy75 = yylhsminor.yy75;
        break;
      case 7: /* ddl ::= drop */
#line 84 "parse.y"
{
    debug_print("ddl: drop");
    yylhsminor.yy75 = new dawn::DDLNode(dawn::DDLType::kDropTable);
    yylhsminor.yy75->add_child(yymsp[0].minor.yy56);
}
#line 1022 "parse.c"
  yymsp[0].minor.yy75 = yylhsminor.yy75;
        break;
      case 8: /* create ::= CREATE TABLE identifier LEFT_PARENTHESES create_def_list RIGHT_PARENTHESES */
#line 90 "parse.y"
{
    debug_print("create: CREATE TABLE identifier '(' create_def_list ')'");
    yymsp[-5].minor.yy3 = new dawn::CreateNode(yymsp[-3].minor.yy2, yymsp[-1].minor.yy42);
}
#line 1031 "parse.c"
        break;
      case 9: /* create_def_list ::= create_def */
#line 95 "parse.y"
{
    debug_print("create_def_list: create_def");
    yylhsminor.yy42 = new dawn::CreateDefListNode();
    yylhsminor.yy42->add_child(yymsp[0].minor.yy66);
}
#line 1040 "parse.c"
  yymsp[0].minor.yy42 = yylhsminor.yy42;
        break;
      case 10: /* create_def_list ::= create_def_list COMMA create_def */
#line 101 "parse.y"
{
    debug_print("create_def_list: create_def_list ',' create_def");
    yymsp[-2].minor.yy42->add_child(yymsp[0].minor.yy66);
    yylhsminor.yy42 = yymsp[-2].minor.yy42;
}
#line 1050 "parse.c"
  yymsp[-2].minor.yy42 = yylhsminor.yy42;
        break;
      case 11: /* create_def ::= col_name column_def */
#line 107 "parse.y"
{
    debug_print("create_def: col_name column_def");
    yylhsminor.yy66 = new dawn::CreateDefNode(yymsp[-1].minor.yy2, yymsp[0].minor.yy25);
}
#line 1059 "parse.c"
  yymsp[-1].minor.yy66 = yylhsminor.yy66;
        break;
      case 12: /* create_def ::= PRIMARY_KEY LEFT_PARENTHESES identifier RIGHT_PARENTHESES */
#line 112 "parse.y"
{
    debug_print("create_def: PRIMARY_KEY '(' identifier ')'");
    yymsp[-3].minor.yy66 = new dawn::CreateDefNode(yymsp[-1].minor.yy2);
}
#line 1068 "parse.c"
        break;
      case 13: /* col_name ::= identifier */
#line 117 "parse.y"
{
    debug_print("col_name: identifier");
    yylhsminor.yy2 = yymsp[0].minor.yy2;
}
#line 1076 "parse.c"
  yymsp[0].minor.yy2 = yylhsminor.yy2;
        break;
      case 14: /* column_def ::= data_type */
#line 122 "parse.y"
{
    debug_print("column_def: data_type");
    yylhsminor.yy25 = new dawn::ColumnDefNode(yymsp[0].minor.yy7);
}
#line 1085 "parse.c"
  yymsp[0].minor.yy25 = yylhsminor.yy25;
        break;
      case 15: /* data_type ::= CHAR LEFT_PARENTHESES INT_NUM RIGHT_PARENTHESES */
#line 127 "parse.y"
{
    debug_print("data_type: CHAR '(' NUMBER ')'");
    yymsp[-3].minor.yy7 = new dawn::DataTypeNode(dawn::TypeId::kChar, yymsp[-1].minor.yy0.val_.integer_);
}
#line 1094 "parse.c"
        break;
      case 16: /* data_type ::= INT */
#line 132 "parse.y"
{
    debug_print("data_type: INT");
    yymsp[0].minor.yy7 = new dawn::DataTypeNode(dawn::TypeId::kInteger);
}
#line 1102 "parse.c"
        break;
      case 17: /* data_type ::= DECIMAL */
#line 137 "parse.y"
{
    debug_print("data_type: DECIMAL");
    yymsp[0].minor.yy7 = new dawn::DataTypeNode(dawn::TypeId::kDecimal);
}
#line 1110 "parse.c"
        break;
      case 18: /* data_type ::= BOOLEAN */
#line 142 "parse.y"
{
    debug_print("data_type: BOOLEAN");
    yymsp[0].minor.yy7 = new dawn::DataTypeNode(dawn::TypeId::kBoolean);
}
#line 1118 "parse.c"
        break;
      case 19: /* identifier ::= ID */
#line 147 "parse.y"
{
    debug_print("identifier: ID");
    yylhsminor.yy2 = new dawn::IdentifierNode(yymsp[0].minor.yy0.val_.varchar_);
    delete[] yymsp[0].minor.yy0.val_.varchar_;
}
#line 1127 "parse.c"
  yymsp[0].minor.yy2 = yylhsminor.yy2;
        break;
      case 20: /* drop ::= DROP TABLE identifier */
#line 153 "parse.y"
{
        debug_print("drop: DROP TABLE identifier");
        yymsp[-2].minor.yy56 = new dawn::DropNode(yymsp[0].minor.yy2);
    }
#line 1136 "parse.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  dawnARG_FETCH
  dawnCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  dawnARG_STORE /* Suppress warning about unused %extra_argument variable */
  dawnCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  dawnTOKENTYPE yyminor         /* The minor type of the error token */
){
  dawnARG_FETCH
  dawnCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 28 "parse.y"

    ast_root->set_error();
#line 1201 "parse.c"
/************ End %syntax_error code ******************************************/
  dawnARG_STORE /* Suppress warning about unused %extra_argument variable */
  dawnCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  dawnARG_FETCH
  dawnCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  dawnARG_STORE /* Suppress warning about unused %extra_argument variable */
  dawnCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "dawnAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void dawn(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  dawnTOKENTYPE yyminor       /* The value for the token */
  dawnARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  dawnCTX_FETCH
  dawnARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor dawnCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int dawnFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
